import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { MainLayout } from "@/components/layout/main-layout";
import { cookies } from "next/headers";
import { ACCESS_TOKEN_COOKIE_KEY } from "@/core";

export const metadata: Metadata = {
  title: "Inquira",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const token = cookie.get(ACCESS_TOKEN_COOKIE_KEY)?.value;
  let initialUser = null;
  if (token) {
    try {
      const res = await fetch(`${process.env.API_BASE_URL}/api/v1/auth/me`, {
        headers: {
          Cookie: `${ACCESS_TOKEN_COOKIE_KEY}=${token}`,
        },
        cache: "no-store",
      });

      if (res.ok) {
        initialUser = await res.json();
      } else if (res.status !== 401) {
        throw new Error("Failed to fetch user data (bad response)");
      }
    } catch (err) {
      throw new Error("Auth service unavailable");
    }
  }
  return (
    <MainLayout initialUser={initialUser}>
      {children}
      <Toaster richColors />
    </MainLayout>
  );
}
